"""baseline

Revision ID: 93c2caa18195
Revises:
Create Date: 2026-02-07 22:41:58.494490

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93c2caa18195"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_entity", "audit_log", ["entity_type", "entity_id"], unique=False)
    op.create_index(op.f("ix_audit_log_company_id"), "audit_log", ["company_id"], unique=False)
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_table(
        "company_holiday",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "date", name="uq_holiday_company_date"),
    )
    op.create_index(op.f("ix_company_holiday_company_id"), "company_holiday", ["company_id"], unique=False)
    op.create_table(
        "time_off_policy",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "key", name="uq_policy_company_key"),
    )
    op.create_index(op.f("ix_time_off_policy_company_id"), "time_off_policy", ["company_id"], unique=False)
    op.create_table(
        "time_off_balance_snapshot",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("accrued_minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("used_minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("held_minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("available_minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["policy_id"], ["time_off_policy.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("company_id", "employee_id", "policy_id"),
    )
    op.create_index(
        op.f("ix_time_off_balance_snapshot_employee_id"), "time_off_balance_snapshot", ["employee_id"], unique=False
    )
    op.create_table(
        "time_off_policy_assignment",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["policy_id"], ["time_off_policy.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "employee_id", "policy_id", "effective_from", name="uq_assignment_employee_policy_from"
        ),
    )
    op.create_index(
        op.f("ix_time_off_policy_assignment_company_id"), "time_off_policy_assignment", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_time_off_policy_assignment_employee_id"), "time_off_policy_assignment", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_time_off_policy_assignment_policy_id"), "time_off_policy_assignment", ["policy_id"], unique=False
    )
    op.create_table(
        "time_off_policy_version",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("accrual_method", sa.String(length=50), nullable=True),
        sa.Column("settings_json", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("change_reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["policy_id"], ["time_off_policy.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_id", "version", name="uq_policy_version_number"),
    )
    op.create_index(
        op.f("ix_time_off_policy_version_policy_id"), "time_off_policy_version", ["policy_id"], unique=False
    )
    op.create_table(
        "time_off_request",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("requested_minutes", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("status", sa.String(length=50), server_default="DRAFT", nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decision_note", sa.String(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["policy_id"], ["time_off_policy.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "employee_id", "idempotency_key", name="uq_request_idempotency"),
    )
    op.create_index("ix_request_company_status", "time_off_request", ["company_id", "status"], unique=False)
    op.create_index(op.f("ix_time_off_request_company_id"), "time_off_request", ["company_id"], unique=False)
    op.create_index(op.f("ix_time_off_request_employee_id"), "time_off_request", ["employee_id"], unique=False)
    op.create_index(op.f("ix_time_off_request_policy_id"), "time_off_request", ["policy_id"], unique=False)
    op.create_index(op.f("ix_time_off_request_status"), "time_off_request", ["status"], unique=False)
    op.create_table(
        "time_off_ledger_entry",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version_id", sa.Uuid(), nullable=False),
        sa.Column("entry_type", sa.String(length=50), nullable=False),
        sa.Column("amount_minutes", sa.Integer(), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["policy_id"], ["time_off_policy.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["policy_version_id"], ["time_off_policy_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_type", "source_id", "entry_type", name="uq_ledger_idempotency"),
    )
    op.create_index("ix_ledger_employee_policy", "time_off_ledger_entry", ["employee_id", "policy_id"], unique=False)
    op.create_index(op.f("ix_time_off_ledger_entry_company_id"), "time_off_ledger_entry", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_time_off_ledger_entry_employee_id"), "time_off_ledger_entry", ["employee_id"], unique=False
    )
    op.create_index(op.f("ix_time_off_ledger_entry_policy_id"), "time_off_ledger_entry", ["policy_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_time_off_ledger_entry_policy_id"), table_name="time_off_ledger_entry")
    op.drop_index(op.f("ix_time_off_ledger_entry_employee_id"), table_name="time_off_ledger_entry")
    op.drop_index(op.f("ix_time_off_ledger_entry_company_id"), table_name="time_off_ledger_entry")
    op.drop_index("ix_ledger_employee_policy", table_name="time_off_ledger_entry")
    op.drop_table("time_off_ledger_entry")
    op.drop_index(op.f("ix_time_off_request_status"), table_name="time_off_request")
    op.drop_index(op.f("ix_time_off_request_policy_id"), table_name="time_off_request")
    op.drop_index(op.f("ix_time_off_request_employee_id"), table_name="time_off_request")
    op.drop_index(op.f("ix_time_off_request_company_id"), table_name="time_off_request")
    op.drop_index("ix_request_company_status", table_name="time_off_request")
    op.drop_table("time_off_request")
    op.drop_index(op.f("ix_time_off_policy_version_policy_id"), table_name="time_off_policy_version")
    op.drop_table("time_off_policy_version")
    op.drop_index(op.f("ix_time_off_policy_assignment_policy_id"), table_name="time_off_policy_assignment")
    op.drop_index(op.f("ix_time_off_policy_assignment_employee_id"), table_name="time_off_policy_assignment")
    op.drop_index(op.f("ix_time_off_policy_assignment_company_id"), table_name="time_off_policy_assignment")
    op.drop_table("time_off_policy_assignment")
    op.drop_index(op.f("ix_time_off_balance_snapshot_employee_id"), table_name="time_off_balance_snapshot")
    op.drop_table("time_off_balance_snapshot")
    op.drop_index(op.f("ix_time_off_policy_company_id"), table_name="time_off_policy")
    op.drop_table("time_off_policy")
    op.drop_index(op.f("ix_company_holiday_company_id"), table_name="company_holiday")
    op.drop_table("company_holiday")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_company_id"), table_name="audit_log")
    op.drop_index("ix_audit_entity", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
